#ENC[AES256_GCM,data:HzJNIjmff4ntj93C0TPxbNW8v890sO7k+0wFN6ILrRcRfiv6ZTa1hjW+Pf97vuk=,iv:MjeKGnuTL7YwUjglM5lfnOiYfZpXnBVEjLr928e8u2E=,tag:hPvM6Zql7layxq/9+WvK2A==,type:comment]
#ENC[AES256_GCM,data:A24gB/2X7stY2lnvvDntA2J6BaYlH4ZulNnYBasixvmVlL77sz042i4hNb3juXDCL/G2WklgLQ==,iv:PqTfhxQ6IBj4rjUE4XdbgAVeClUb1Qv29MFgxMuBy0A=,tag:hWL0RicjUOLMsb2uLBsYAQ==,type:comment]
#ENC[AES256_GCM,data:IgTrJBF5fU2+Xed89bbkSdrtmhpDW9KBZhm7HA1ZBMUkf/q3KjafC3hcuEN1M8Y=,iv:RJSoRuNILtPswTpkX5KAQpBPScZPu0jv5B3umj+BIw8=,tag:Us0FQSGcqUy905pfzQV4EA==,type:comment]
#ENC[AES256_GCM,data:pfmrUI+lvRdGlAKELMYhOsIwBSkhmFRmmVralSRzML4fWJbUge5VT069I/BUt/rL,iv:xyZwN7/HElnN+95FgDQHm0lbHQSsrgx6+Xjq4QKsHYI=,tag:KS2ynXEi4avC/xPO6e3sjw==,type:comment]
#ENC[AES256_GCM,data:M0pthKSaIqMk0nshbM3ylrm6OZ7eKluFWMd8mTFKvj5YINryCsutfoSjmOeuEppxx+nDXYU=,iv:umYCthx2UJp1Re7OoeJ/nflR3dJdqa6clsPwVe6/XUU=,tag:OawWgWHTP0iuouvEY7iqng==,type:comment]
#ENC[AES256_GCM,data:FCnK+BdzKgLJ2sk61QaymDWHZqXjW1Pve6maxEPY6BRpwszMhivdzhM+9VKYm60=,iv:CrPZFSYQAnSCTaJ0Q+MTWezOH3srMNHiXgxFkp6AyUI=,tag:xI1nke3x4q8I6gmdC0HqPg==,type:comment]
grafana:
    adminUser: ENC[AES256_GCM,data:SDSH/z4=,iv:tVgE2KY6C+9x5H0Cleaz8LpOFLN4g3N55Nde5SOFf/Q=,tag:aIXtKx0xR06bUgRhgdNnAg==,type:str]
    adminPassword: ENC[AES256_GCM,data:3ms7ggg=,iv:7dak4j3zYA5Oh2NlX1+3lW5bSaf8nT42WySTpWoLTGY=,tag:w0e1Q/rWPHDjcqNdd0b+hg==,type:str]
sops:
    age:
        - recipient: age1s02kpsyqeuz62heh2ds7jvqxkex7xezhnjgr8ha6e4sudpyv49fqtuetht
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJVjVFeHROcjlyOWZFbmYv
            aytmaTVQL0ZvQ2FlNERCbm94UU1XVnFhZFFFClplYnJTcG9oUTVwcVJoamtvSFRG
            MGpVSEFQZDg0MnM1TytNMERSRm1MOXcKLS0tIGlLUVZLOHVONUlMLzk1VUd6YnpJ
            ZDE1N3FCZy96MmcramwxZkZGdE1QMGsKoCPwID4wTCquR7QHtOqlOeJlakmW7ugI
            aDIpviVs9ac9CufOQRa6NlR9sfoHJVjNV1AIGEGAR/ws/tZpvX4jog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T13:49:06Z"
    mac: ENC[AES256_GCM,data:HINsyy2SB351jCnwt5CbTzQEWkwgFEk7EOSwN0Y5SWXyqZtMaBLLpVQBsgiNOMYB8znOFjL4Frgd8drAAkCSlwUjU24qZsM//NjNAFHHIqgmYDF84TLxLx/U9GyXmjNknMZS2imQ0VWFMvq8Phf+9eHafsGpT2xrhSVyqwf493E=,iv:OSDV/qTGIOV8x+NfGma5zKYBzzbOPT61CkDwBPRQUQ0=,tag:HmkhwrfQq6W2CFVJ+nuUhg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
