#ENC[AES256_GCM,data:j35Rh399Yt4MRKaBp6JtPUq/U8cxumaN0ZnoFd5rax5QkhanhBcAoskaGsJ+u60=,iv:0uEx6Sy4M6CIUJxdCyOqbZSu0v4dwAAPSfywz3QINjc=,tag:ERO/2w/w0Sx0hQk4/R7jZQ==,type:comment]
#ENC[AES256_GCM,data:zHruR6AUi5APKTrEUWUd/G+Gtwmcp2MkY8Ni5esY8sj6JrFyrellJbIlm12qa1V6++mhsipsDA==,iv:yhzpBRKfS/PQgthQAH+L5gPe9hUcsfrIQENMXFuj8kM=,tag:oPtXk78FiH46qwCPOHZ84w==,type:comment]
#ENC[AES256_GCM,data:xKpiaZlcHTnrslYKRm27Bz7oTWgf+zDYR4+qepwxsN4AqSI4sQQwMsvEbT9bVH4=,iv:iWD43Nm6crBGaxsNEmbm+OxGi/e8xgX8DgDmM0al2/8=,tag:zvbALFcs9HQE5Q/laqVOfw==,type:comment]
#ENC[AES256_GCM,data:YSIeMiVXqkHT6NcEOz0nUX68Od2o1+OVRccqZTxtZfTUMzPyuS2Sw6ZOlaYWsoUmx/cqQgo=,iv:dAnxxy6McyPff/PP7X8sPoI42IyDOBnJnvAK0ZIhm+s=,tag:OWsgeph2XmUSCHc5pS4mtA==,type:comment]
#ENC[AES256_GCM,data:xG9zb47tBGkjZa4NKkwzKu1q1M086oGqZAlmh10qd39SeGivH+PY8y00ZJyI2XGVN3JCZ5ZPOohRRoZ48TjBlfoquT2vFlEF1arLnDDORtRfJDQ=,iv:XcAHKl6ih6TZn1IraGhGxP+sK/6T5X7CCoj7fZZtJ/4=,tag:xVBgMl9kas0RMSSypF7VHA==,type:comment]
#ENC[AES256_GCM,data:e7haXCVTPVY0iBpXv8bFaeNmWmWGueiOEWcavqm7JVdgt+1WXZiu9SBhBS0ZtcsNujLxSKDKgh+W8DuuXdt+eSpAQ3BF9f6W12nE3Im3RB4dJvk0JAs=,iv:OGB3fApZei9pMUVqVVrtofhP7fZLyG4Mk1mdiTreCbo=,tag:wGibVLeDIPiDBTn/T9jOaw==,type:comment]
#ENC[AES256_GCM,data:KXqgD89cRyyaQeCjiMS2wg/Z8sPNlTO0v4gJ3eW6YRcJmwB4x5YAH/CbTN5MMDs=,iv:kG3UAhNFcJoP37y0zE8RLuJYb73RBwBHX2WhFimHFMc=,tag:IRuT6ldgGNJQcTXHajYy1w==,type:comment]
auth:
    rootUsername: ENC[AES256_GCM,data:1wVFwZ8=,iv:f4eJbjAnA4xy003M0HdDEwv1ByFC6qhdX5Bwnj9voR4=,tag:HoVt7LSpET56/lLB1AsDQA==,type:str]
    rootPassword: ENC[AES256_GCM,data:+mtlfuNEYrcEW0HPDg==,iv:yrpOkI7d6/AdDZvs09bCW4GgYiJhmgb+g2cEq/ZjDcw=,tag:0CxquKBgwE7H6arRMAShhA==,type:str]
sops:
    age:
        - recipient: age1s02kpsyqeuz62heh2ds7jvqxkex7xezhnjgr8ha6e4sudpyv49fqtuetht
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAweXVrMkdkVU1mSnBqSzA1
            T3dmSTNNeFBOaGN2bFNSWGIybEtEYzRJa0Q4CmJVd0hSQUQ2dDd3Z0ZCdWZlTGxo
            TGhYdzc0RTQ1bEs2TlRXcU41ck11cEEKLS0tIGpTQWVpYkFYUXlCSDJLVmNMMnJV
            TmpWbmFOTWFHdm1BT1E4Zld6SklRSG8Kp48hJZy7/arAveaYYIHobrd/VGxoW2EI
            53WchvoF/sxxXv2bdUvoi8MSEnBMAd9PPPeXfxUxsHmgroQMhtNPOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T13:49:06Z"
    mac: ENC[AES256_GCM,data:P7gmGFPkGkbw5819ip8y9k8Tr1Q47Je63iP3zH4IwSoOkwrNx2ErkjVUydA0dw457QWZbvYU4rvS9CI16YxANzPRZsrd0cAohn6uPQQZI6j92o5ixHweRiI3R3BBlIRQToi/4fwPWnscoGEfGIFkh1slEgSpjdH6VNAFqeitPqw=,iv:tYmuCErijbjOxsLt0aNfY09CFeBLWEmfnlH+urwJU8Q=,tag:noCXg6efpbAGMDVkG9CRXQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
