# ==============================================
# ArgoCD Application: Harbor Container Registry
# ==============================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: study-ckad
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: study-ckad

  source:
    repoURL: https://helm.goharbor.io
    chart: harbor
    targetRevision: "1.18.3"
    helm:
      valuesObject:
        expose:
          type: nodePort
          tls:
            enabled: false
        externalURL: http://core.harbor.local
        harborAdminPassword: Harbor12345
        persistence:
          enabled: false
        trivy:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: harbor

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
